package cn.ms08.apiconvert.exception;

public enum ErrorCode {
    INVALID_REQUEST,
    UNAUTHORIZED,
    FORBIDDEN,
    MODEL_NOT_FOUND,
    PROVIDER_NOT_FOUND,
    PROVIDER_UNAVAILABLE,
    PROVIDER_AUTH_FAILED,
    PROVIDER_RATE_LIMITED,
    PROVIDER_TIMEOUT,
    PROVIDER_BAD_RESPONSE,
    ROUTE_NOT_FOUND,
    UNSUPPORTED_FEATURE,
    QUOTA_INSUFFICIENT,
    INTERNAL_ERROR
}
