import { createApp, type Component } from 'vue'
import App from './App.vue'
import router from './router'
import {
  NAlert,
  NButton,
  NCard,
  NConfigProvider,
  NDataTable,
  NDatePicker,
  NDescriptions,
  NDescriptionsItem,
  NDialogProvider,
  NDropdown,
  NForm,
  NFormItem,
  NGrid,
  NGridItem,
  NH2,
  NIcon,
  NInput,
  NInputGroup,
  NInputNumber,
  NLayout,
  NLayoutContent,
  NLayoutHeader,
  NLayoutSider,
  NMenu,
  NMessageProvider,
  NModal,
  NNotificationProvider,
  NPagination,
  NSelect,
  NSpace,
  NStatistic,
  NSwitch,
  NTabPane,
  NTabs,
  NTag,
  NText,
  NTooltip,
} from 'naive-ui'
import './styles/global.css'

const app = createApp(App)
app.use(router)
const naiveComponents: [string, Component][] = [
  ['NAlert', NAlert],
  ['NButton', NButton],
  ['NCard', NCard],
  ['NConfigProvider', NConfigProvider],
  ['NDataTable', NDataTable],
  ['NDatePicker', NDatePicker],
  ['NDescriptions', NDescriptions],
  ['NDescriptionsItem', NDescriptionsItem],
  ['NDialogProvider', NDialogProvider],
  ['NDropdown', NDropdown],
  ['NForm', NForm],
  ['NFormItem', NFormItem],
  ['NGrid', NGrid],
  ['NGridItem', NGridItem],
  ['NH2', NH2],
  ['NIcon', NIcon],
  ['NInput', NInput],
  ['NInputGroup', NInputGroup],
  ['NInputNumber', NInputNumber],
  ['NLayout', NLayout],
  ['NLayoutContent', NLayoutContent],
  ['NLayoutHeader', NLayoutHeader],
  ['NLayoutSider', NLayoutSider],
  ['NMenu', NMenu],
  ['NMessageProvider', NMessageProvider],
  ['NModal', NModal],
  ['NNotificationProvider', NNotificationProvider],
  ['NPagination', NPagination],
  ['NSelect', NSelect],
  ['NSpace', NSpace],
  ['NStatistic', NStatistic],
  ['NSwitch', NSwitch],
  ['NTabPane', NTabPane],
  ['NTabs', NTabs],
  ['NTag', NTag],
  ['NText', NText],
  ['NTooltip', NTooltip],
]

naiveComponents.forEach(([name, component]) => {
  app.component(name, component)
})
app.mount('#app')
